name: trip
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  table_calendar: ^3.1.2
  intl: ^0.20.2
  provider: ^6.1.2   # 👈 ADD THIS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#EAA21B"
  image: assets/icons/Habesha_Wings_logo.PNG
  android: true
  ios: true
  android_12:
    color: "#EAA21B"
    image: assets/icons/Habesha_Wings_logo.PNG
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
